url: "https://rudolph.moe.estl" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/faq" # the subpath of your site, e.g. /blog
title: "MOE School Bus" # the name of your site, e.g. ACME Corp.
